# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # run Unit tests
      run_tests(
       scheme: "GBShopRSN",
       workspace: "GBShopRSN.xcworkspace",
       device: "iPhone SE (2nd generation)",
       testplan: "FastTests"
      )
    
    # run UI tests
      run_tests(
       scheme: "GBShopRSN",
       workspace: "GBShopRSN.xcworkspace",
       device: "iPhone SE (2nd generation)",
       testplan: "SlowTests"
      )
  end
end
